"""
Django settings for ***REMOVED*** project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

ENV = os.getenv('ENVIRONMENT', 'development')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(y&@n=h*tby&y+a&7lnt0z0nzp7d=-$x#-ieq+tzuhs*_$*8wj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV == 'development'

ALLOWED_HOSTS = [
    '***REMOVED***2.tc-***REMOVED***.org',
    'localhost'
]


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'rest_framework',
    'corsheaders',
]

APPLICATION_APPS = [
    'messages',
]

INSTALLED_APPS = DJANGO_APPS + EXTERNAL_APPS + APPLICATION_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '***REMOVED***.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '***REMOVED***.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'local': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '***REMOVED***',
        'USER': '***REMOVED***',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': 3306
    },
    'development': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '***REMOVED***',
        'USER': '***REMOVED***',
        'PASSWORD': '***REMOVED***',
        'HOST': 'mailer-dev.c3ecka0pmtwy.us-east-1.rds.amazonaws.com',
        'PORT': 3306
    },
    'production': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '***REMOVED***',
        'USER': '***REMOVED***',
        'PASSWORD': '***REMOVED***',
        'HOST': 'mailer-dev.c3ecka0pmtwy.us-east-1.rds.amazonaws.com',
        'PORT': 3306
    }
}
DATABASES['default'] = DATABASES[ENV]


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Rest Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}


# CORS Settings
CORS_ORIGIN_ALLOW_ALL = True
