# Generated by Django 2.1.4 on 2018-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_auto_20181211_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc_emails',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_emails',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
